imatic_controller:
    resources_config:
        prototype:
            actions:
                list:
                    template: ImaticViewBundle:Crud:list.html.twig
                    type: list
                    group: list
                    route: { methods: [get], path: "/" }
                    controller: ImaticControllerBundle:Resource/List:list
                autocomplete:
                    type: autocomplete
                    group: api
                    route: { methods: [get], path: "/autocomplete" }
                    controller: ImaticControllerBundle:Resource/Autocomplete:autocomplete
                create:
                    template: ImaticViewBundle:Crud:edit.html.twig
                    type: create
                    group: list
                    route: { methods: [post, get], path: "/create" }
                    controller: ImaticControllerBundle:Resource/Create:create
                    command: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\CreateHandler
                    redirect: show
                    extra:
                        button_data: {ajaxify: false}
                show:
                    template: ImaticViewBundle:Crud:show.html.twig
                    type: show
                    group: item
                    route: { methods: [get], path: "/{id}", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Show:show
                    extra:
                        button_data: {target: modal, modal-size: large, modal-on-close: '@current'}
                delete:
                    template: ImaticViewBundle:Crud:delete.html.twig
                    type: delete
                    group: item
                    route: { methods: [delete, get], path: "/{id}/delete", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Delete:delete
                    command: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\DeleteHandler
                    redirect: list
                    extra:
                        button_data: {method: delete, confirm: 'Are you sure?'}
                        button_parent: show
                edit:
                    template: ImaticViewBundle:Crud:edit.html.twig
                    type: edit
                    group: item
                    route: { methods: [put, get], path: "/{id}/edit", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Edit:edit
                    command: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\EditHandler
                    redirect: list
                    extra:
                        button_data: {target: modal, modal-size: large, data-modal-close-on-form-success: 'true'}
                        button_parent: show
                batch:
                    type: batch
                    group: batch
                    route: { methods: [put], path: "/batch" }
                    redirect: list
                    controller: ImaticControllerBundle:Resource/Batch:batch
