imatic_controller:
    resources_config:
        prototype:
            actions:
                list:
                    template: ImaticViewBundle:Crud:list.html.twig
                    type: list
                    group: list
                    route: { methods: [get], path: "/" }
                    controller: ImaticControllerBundle:Resource/List:list
                autocomplete:
                    type: autocomplete
                    group: api
                    route: { methods: [get], path: "/autocomplete" }
                    controller: ImaticControllerBundle:Resource/Autocomplete:autocomplete
                create:
                    template: ImaticViewBundle:Crud:edit.html.twig
                    type: create
                    group: list
                    route: { methods: [post, get], path: "/create" }
                    controller: ImaticControllerBundle:Resource/Create:create
                    command: imatic_data.generic_create
                show:
                    template: ImaticViewBundle:Crud:show.html.twig
                    type: show
                    group: item
                    route: { methods: [get], path: "/{id}", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Show:show
                delete:
                    type: delete
                    group: item
                    route: { methods: [delete], path: "/{id}", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Delete:delete
                    command: imatic_data.generic_delete
                    extra:
                        button_data: {method: delete, confirm: 'Are you sure?'}
                        button_parent: show
                edit:
                    template: ImaticViewBundle:Crud:edit.html.twig
                    type: edit
                    group: item
                    route: { methods: [put, get], path: "/{id}/edit", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Edit:edit
                    command: imatic_data.generic_edit
                    extra:
                        button_parent: show
                batch:
                    type: batch
                    group: batch
                    route: { methods: [put, get], path: "/batch" }
                    controller: ImaticControllerBundle:Resource/Batch:batch
