imatic_controller:
    resources_config:
        prototype:
            actions:
                list:
                    template: ImaticViewBundle:Crud:list.html.twig
                    type: list
                    group: page
                    collection: true
                    route: { methods: [get], path: "/" }
                    controller: ImaticControllerBundle:Resource/List:list
                autocomplete:
                    type: autocomplete
                    group: api
                    collection: true
                    route: { methods: [get], path: "/autocomplete" }
                    controller: ImaticControllerBundle:Resource/Autocomplete:autocomplete
                create:
                    template: ImaticViewBundle:Crud:edit.html.twig
                    type: create
                    group: page
                    collection: true
                    route: { methods: [post, get], path: "/create" }
                    controller: ImaticControllerBundle:Resource/Create:create
                show:
                    template: ImaticViewBundle:Crud:show.html.twig
                    type: show
                    group: object
                    collection: false
                    route: { methods: [get], path: "/{id}", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Show:show
                delete:
                    type: delete
                    group: object
                    collection: false
                    route: { methods: [delete], path: "/{id}", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Delete:delete
                edit:
                    template: ImaticViewBundle:Crud:edit.html.twig
                    type: edit
                    group: object
                    collection: false
                    route: { methods: [put, get], path: "/{id}/edit", requirements: { id: '\d+' } }
                    controller: ImaticControllerBundle:Resource/Edit:edit
                batch:
                    type: batch
                    group: batch
                    collection: true
                    route: { methods: [put, get], path: "/batch" }
                    controller: ImaticControllerBundle:Resource/Batch:batch
