imatic_controller:
    resources_config:
        defaults:
            list:
                template: ImaticViewBundle:Crud:list.html.twig
                type: list
                collection: true
                route: { methods: [get], path: / }
                controller: ImaticControllerBundle:Resource/List:list
            autocomplete:
                type: autocomoplete
                collection: true
                route: { methods: [get], path: /autocomplete }
                controller: ImaticControllerBundle:Resource/Autocomplete:autocomplete
            create:
                template: ImaticViewBundle:Crud:edit.html.twig
                type: create
                collection: true
                route: { methods: [post], path: / }
                controller: ImaticControllerBundle:Resource/Create:create
            show:
                template: ImaticViewBundle:Crud:show.html.twig
                type: show
                collection: false
                route: { methods: [get], path: /:id }
                controller: ImaticControllerBundle:Resource/Show:show
            delete:
                type: delete
                collection: false
                route: { methods: [delete], path: /:id }
                controller: ImaticControllerBundle:Resource/Delete:delete
            edit:
                template: ImaticViewBundle:Crud:edit.html.twig
                type: edit
                collection: false
                route: { methods: [put, get], path: /:id/edit }
                controller: ImaticControllerBundle:Resource/Edit:edit
            batch:
                type: batch
                collection: true
                route: { methods: [put, get], path: /batch }
                controller: ImaticControllerBundle:Resource/Batch:batch
        required:
            all:
                - entity
                - type
                - collection
                - route
                - query
                - controller
            list:
                - template
            autocomplete:
            create:
                - template
                - form
                - command
                - redirect
            show:
                - template
            delete:
                - command
                - redirect
            edit:
                - template
                - form
                - command
                - redirect
            batch:
                - command
                - redirect
