parameters:
    imatic_importexport.file_import.class: Imatic\Bundle\ControllerBundle\ImportExport\Import\File\FileImport

services:
    imatic_controller.api.export:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Export\ExportApi
        arguments:
            - '@imatic_controller.api.feature.request'
            - '@imatic_controller.api.feature.response'
            - '@imatic_importexport.exporter'
            - '@imatic_controller.api.download'
            - '@imatic_data.filter_factory'
        shared: false

    imatic_controller.api.import:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Import\ImportApi
        arguments:
            - '@imatic_controller.api.feature.request'
            - '@imatic_controller.api.feature.response'
            - '@imatic_controller.api.feature.template'
            - '@imatic_controller.api.feature.redirect'
            - '@imatic_importexport.importer'
        shared: false

    imatic_controller.file_transformer:
        class: Imatic\Bundle\ControllerBundle\ImportExport\Import\File\FileTransformer
        arguments:
            - '@form.factory'
            - '@imatic_data.command_executor'
        tags:
            - { name: kernel.event_subscriber }
