services:
    # api - features
    imatic_controller.api.feature.data:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Data\DataFeature
        arguments:
            - @imatic_data.query_executor

    imatic_controller.api.feature.template:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Template\TemplateFeature
        arguments:
            - @templating

    imatic_controller.api.feature.form:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Form\FormFeature
        arguments:
            - @form.factory

    imatic_controller.api.feature.response:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Response\ResponseFeature

    imatic_controller.api.feature.request:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Request\RequestFeature
        arguments:
            - @request_stack
            - @imatic_controller.display_criteria_factory

    imatic_controller.api.feature.command:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Command\CommandFeature
        arguments:
            - @imatic_data.command_executor
            - @imatic_data.command_handler_repository
            - @imatic_controller.api.feature.framework.bundle_guesser

    imatic_controller.api.feature.redirect:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Redirect\RedirectFeature
        arguments:
            - @router

    imatic_controller.api.feature.message:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Message\MessageFeature
        arguments:
            - @session
            - @translator

    imatic_controller.api.feature.framework.bundle_guesser:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Framework\BundleGuesserFeature
        arguments:
            - @kernel

    # api - concrete
    imatic_controller.api.show:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Show\ShowApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.data
        tags:
            - { name: imatic_controller.api, alias: show }

    imatic_controller.api.listing:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Listing\ListingApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.data
        tags:
            - { name: imatic_controller.api, alias: listing }

    imatic_controller.api.form:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Form\FormApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
            - @imatic_controller.api.feature.form
            - @imatic_controller.api.feature.data
            - @imatic_controller.api.feature.template
        tags:
            - { name: imatic_controller.api, alias: form }

    imatic_controller.api.command:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Command\CommandApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
        tags:
            - { name: imatic_controller.api, alias: command }

    imatic_controller.api.command.object:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Command\ObjectCommandApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
            - @imatic_controller.api.feature.data
        tags:
            - { name: imatic_controller.api, alias: objectCommand }

    # api - common
    imatic_controller.api_repository:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\ApiRepository

    # display criteria
    imatic_controller.display_criteria_factory:
        class: Imatic\Bundle\ControllerBundle\Request\Query\DisplayCriteriaFactory
        arguments:
            - @request_stack
            - @imatic_data.pager_factory
