parameters:
    imatic_importexport.file_import.class: Imatic\Bundle\ControllerBundle\ImportExport\Import\File\FileImport

services:
    # api - features
    imatic_controller.api.feature.data:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Data\DataFeature
        arguments:
            - @imatic_data.query_executor
        scope: prototype

    imatic_controller.api.feature.template:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Template\TemplateFeature
        arguments:
            - @templating
        scope: prototype

    imatic_controller.api.feature.form:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Form\FormFeature
        arguments:
            - @form.factory
        scope: prototype

    imatic_controller.api.feature.response:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Response\ResponseFeature
        scope: prototype

    imatic_controller.api.feature.request:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Request\RequestFeature
        arguments:
            - @request_stack
            - @imatic_data.display_criteria_factory
        scope: prototype

    imatic_controller.api.feature.command:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Command\CommandFeature
        arguments:
            - @imatic_data.command_executor
            - @imatic_data.command_handler_repository
        scope: prototype

    imatic_controller.api.feature.redirect:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Redirect\RedirectFeature
        arguments:
            - @router
            - @request_stack
        scope: prototype

    imatic_controller.api.feature.message:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Message\MessageFeature
        arguments:
            - @session
            - @translator
        scope: prototype

    # api - concrete
    imatic_controller.api.show:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Show\ShowApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.data
        scope: prototype

    imatic_controller.api.listing:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Listing\ListingApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.data
            - @imatic_data.display_criteria_reader
            - @imatic_data.filter_factory
        scope: prototype

    imatic_controller.api.form:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Form\FormApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
            - @imatic_controller.api.feature.form
            - @imatic_controller.api.feature.data
            - @imatic_controller.api.feature.template
        scope: prototype

    imatic_controller.api.command:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Command\CommandApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
        scope: prototype

    imatic_controller.api.command.object:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Command\ObjectCommandApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
            - @imatic_controller.api.feature.data
        scope: prototype

    imatic_controller.api.command.batch:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Command\BatchCommandApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.command
            - @imatic_controller.api.feature.redirect
            - @imatic_controller.api.feature.message
        scope: prototype

    imatic_controller.api.download:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Download\DownloadApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.data
        scope: prototype

    imatic_controller.api.autocomplete:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Ajax\AutocompleteApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.data
        scope: prototype

    imatic_controller.api.export:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Export\ExportApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_importexport.exporter
            - @imatic_controller.api.download
            - @imatic_data.filter_factory
        scope: prototype

    imatic_controller.api.import:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Import\ImportApi
        arguments:
            - @imatic_controller.api.feature.request
            - @imatic_controller.api.feature.response
            - @imatic_controller.api.feature.template
            - @imatic_controller.api.feature.redirect
            - @imatic_importexport.importer
        scope: prototype

    imatic_controller.file_transformer:
        class: Imatic\Bundle\ControllerBundle\ImportExport\Import\File\FileTransformer
        arguments:
            - @form.factory
            - @imatic_data.command_executor
        tags:
            - { name: kernel.event_subscriber }
