services:
    # api - features
    imatic_controller.api.feature.data:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Data\Data
        arguments:
            - @imatic_data.query_executor

    imatic_controller.api.feature.template:
        class: Imatic\Bundle\ControllerBundle\Controller\Feature\Template\Template
        arguments:
            - @templating

    # api - concrete
    imatic_controller.api.show:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Show\ShowApi
        arguments:
            - @imatic_controller.api.feature.data
            - @imatic_controller.api.feature.template
        tags:
            - { name: imatic_controller.api, alias: show }

    imatic_controller.api.listing:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\Listing\ListingApi
        arguments:
            - @imatic_controller.api.feature.data
            - @imatic_controller.api.feature.template
        tags:
            - { name: imatic_controller.api, alias: listing }

    # api - common
    imatic_controller.api_repository:
        class: Imatic\Bundle\ControllerBundle\Controller\Api\ApiRepository

    # display criteria
    imatic_controller.display_criteria_factory:
        class: Imatic\Bundle\ControllerBundle\Request\Query\DisplayCriteriaFactory
        arguments:
            - @request_stack
            - @imatic_data.pager_factory
